Feature/appointment
MirabbosMirzakhmedov/mroom pull request #17
Opened 2021-10-25 13:08 UTC by MirabbosMirzakhmedov

2021-11-20 15:03 UTC, robertsgreibers requested changes
Added comments @MirabbosMirzakhmedov

2021-11-20 15:03 UTC, robertsgreibers commented on mroom/api/serializer/appointment.py
> +                   'cannot have more less than 9 and more than 15 characters.'
"cannot have MORE LESS" - sounds a bit off, seems like a typo. Fix it.

2021-12-13 18:05 UTC, robertsgreibers commented on mroom/api/serializer/barber.py
> +        ]
I still have this file in your project

2021-12-13 18:08 UTC, robertsgreibers commented on mroom/api/serializer/appointment.py
> +                   'cannot have more less than 9 and more than 15 characters.'
`'Phone number must be between 9, 15 letters and cannot have blank spaces.'` string is too long for one line - it goes over 79 chars. 

Correct format:

```python
    default_error_messages = {
        'invalid': 'Phone number must be between '
                   '9, 15 letters and cannot have blank spaces.'
    }
```

Message has wrong information, it should be about characters/digits not letters. Phone number cannot have letters.

A proper message:

```
Phone number must be between 9 - 15 digits and cannot have blank spaces.
```

2021-12-13 19:22 UTC, MirabbosMirzakhmedov commented on mroom/api/serializer/appointment.py
> +                   'cannot have more less than 9 and more than 15 characters.'
Done

2021-12-30 22:32 UTC, robertsgreibers requested changes
Small change, all the other things seem to be working. @MirabbosMirzakhmedov

2021-12-30 22:32 UTC, robertsgreibers commented on mroom/api/serializer/appointment.py
> +        datetime_object = datetime.strptime(date, "%Y-%m-%dT%H:%M")
Requires additional handling in case an empty `date` is submitted.

I left a comment about it in frontend PR.

2021-12-30 22:32 UTC, robertsgreibers commented on mroom/api/serializer/appointment.py
> +        datetime_object = datetime.strptime(date, "%Y-%m-%dT%H:%M")
Also `'` instead of `"`

2022-01-04 11:41 UTC, MirabbosMirzakhmedov commented on mroom/api/serializer/appointment.py
> +        datetime_object = datetime.strptime(date, "%Y-%m-%dT%H:%M")
Done

2022-01-04 21:12 UTC, robertsgreibers requested changes
small if condition change

2022-01-04 21:12 UTC, robertsgreibers commented on mroom/api/serializer/appointment.py
> +            )
Make it pythonic, read [PEP8](https://www.python.org/dev/peps/pep-0008/):

<img width="810" alt="PEP 8 -- Style Guide for Python Code | Python org 2022-01-04 23-03-32" src="https://user-images.githubusercontent.com/12160621/148123760-c7d38199-be51-42a9-bacc-a3ed9fc854a2.png">


```python
        if not date:
            raise serializers.ValidationError(
                'This field may not be blank.'
            )
```

2022-01-04 21:40 UTC, merged