Feature/barbers
MirabbosMirzakhmedov/mroom pull request #18
Opened 2022-01-03 19:42 UTC by MirabbosMirzakhmedov

2022-01-05 15:51 UTC, robertsgreibers requested changes
Also, appointment endpoint is missing since you haven't merged master branch here yet. 

![Screenshot 2022-01-05 at 17 39 34](https://user-images.githubusercontent.com/12160621/148245489-863d7be3-8702-4df8-a3d9-c0f945020b09.png)

### TO-DO (do it in sequence)
- 1. Merge `master` branch in `feature/barbers`
- 2. Make sure all tests work
- 3. Adjust Appointment model (see explanation below)

### Adjust Appointment model (instructions)

Adjust Appointment model in a way `barber` field is using `models.ForeignKey` with a relationship to `User` model (very similar to what's done in `Session` model with `user` field), see example below:

barber = models.ForeignKey(
    to=User,
    on_delete=models.CASCADE,
    related_name='appointments'
)

which will give you an option to access barber's appointments via dot, see example:

barber_user = User.objects.get(email="roberts@mroom.com", is_barber=True)
print(barber_user.appointments)

Once you adjust Appointment your AppointmentSerializer is not going to work because of the change in barber field. 

You need to adjust your AppointmentSerializer to "lookup" a barber user using a uid value passed from frontend.

Remember, '<option value="' + barber.uid + '">' + barber.name +'</option>'

When user submits appointment form, you send a POST request containing barber.uid value (see above option example) 

In backend you have to use this barber.uid to find such barber in database.

This can be done with

2022-01-05 15:51 UTC, robertsgreibers commented on mroom/api/views.py
> +    queryset = User.objects.all().filter(is_barber=True)
Remove `.all()` part, when you use filter you don't need `.all()` just `queryset = User.objects.filter(is_barber=True)` is fine.

2022-01-06 22:08 UTC, MirabbosMirzakhmedov commented on mroom/api/tests.py
> +class TestBarber(TestCase):
Merged done

2022-01-06 22:08 UTC, MirabbosMirzakhmedov commented on mroom/api/tests.py
> +
Done

2022-01-06 22:09 UTC, MirabbosMirzakhmedov commented on mroom/api/views.py
> +    queryset = User.objects.all().filter(is_barber=True)
Done

2022-01-12 20:38 UTC, robertsgreibers requested changes
I found the real reason your user authentication didn't work - check comments & fix. @MirabbosMirzakhmedov

2022-01-12 20:38 UTC, robertsgreibers commented on mroom/api/tests.py
>              content_type='application/json',
In this test, there's a problem with the last assert (see screenshots below)

`'uid' and 'name'` line evaluates to result `'name'`

![Screenshot 2022-01-12 at 22 10 27](https://user-images.githubusercontent.com/12160621/149214229-27e2cf08-24ef-486e-bd30-c3429cda5445.png)



### Correct way

```python
        self.assertEqual(str(user.uid), res.data['uid'])
        self.assertEqual(user.name, res.data['name'])
```

![mroom – tests py 2022-01-12 22-06-10](https://user-images.githubusercontent.com/12160621/149214077-b4c9c778-a604-4abd-8f06-51d72b67ca13.png)
![mroom – tests py 2022-01-12 22-08-16](https://user-images.githubusercontent.com/12160621/149214081-bfe0ef58-f743-42c1-afef-a72180ce285d.png)

2022-01-12 20:38 UTC, robertsgreibers commented on mroom/api/tests.py
>              'date': '2022-10-27T10:01'
This test will fail with "date from the past used" error when we will reach October 27th of 2022.

Instead of using a string for a valid future date - use:

```python
        appointment_date: str = (
            timezone.now() + timedelta(days=1)
        ).strftime('%Y-%m-%dT%H:%M')
```

![mroom – tests py 2022-01-12 22-21-22](https://user-images.githubusercontent.com/12160621/149215797-0f281ab8-f579-4238-90c1-eb0e3760cc03.png)

2022-01-12 20:38 UTC, robertsgreibers commented on mroom/api/models.py
> +    is_active = models.BooleanField(default=False)
Here's the real reason your user authentication doesn't work anymore.

From sign-in endpoint development document:
![step_3 MD - Grip 2022-01-12 22-29-10](https://user-images.githubusercontent.com/12160621/149216783-092dccbb-de0d-4e2f-bb21-4b3abd3e24eb.png)

You need to change the default value for `is_active` field or explicitly set `is_active` field in sign-in view when you create a new `Session` object.

![mroom – views py 2022-01-12 22-30-48](https://user-images.githubusercontent.com/12160621/149217042-21cf63a6-ed63-47c8-9dd4-0a568c669258.png)

2022-01-12 20:38 UTC, robertsgreibers commented on mroom/settings.py
>  import datetime
Since you changed how you use `timedelta`, `import datetime` is not used anymore and can be removed

2022-01-12 20:40 UTC, robertsgreibers commented on mroom/api/tests.py
> +
Resolved.

2022-01-12 20:40 UTC, robertsgreibers commented on mroom/api/tests.py
> +class TestBarber(TestCase):
Resolved.

2022-01-12 20:41 UTC, robertsgreibers commented on mroom/api/views.py
> +    queryset = User.objects.all().filter(is_barber=True)
Resolved.

2022-01-14 09:19 UTC, MirabbosMirzakhmedov commented on mroom/api/authentication/api.py
> +                is_active=False,
Changed

2022-01-14 09:20 UTC, MirabbosMirzakhmedov commented on mroom/api/models.py
> +
Removed it

2022-01-14 09:20 UTC, MirabbosMirzakhmedov commented on mroom/api/tests.py
>              content_type='application/json',
Yes done

2022-01-14 09:20 UTC, MirabbosMirzakhmedov commented on mroom/api/tests.py
>              'date': '2022-10-27T10:01'
Fixed

2022-01-14 09:20 UTC, MirabbosMirzakhmedov commented on mroom/api/models.py
> +    is_active = models.BooleanField(default=False)
Yes fixed

2022-01-14 09:20 UTC, MirabbosMirzakhmedov commented on mroom/settings.py
>  import datetime
Yes removed

2022-01-14 16:13 UTC, robertsgreibers commented on mroom/api/authentication/api.py
> +                is_active=False,
Resolved.

2022-01-14 16:17 UTC, robertsgreibers commented on mroom/api/models.py
> +    is_active = models.BooleanField(default=False)
Resolved.

2022-01-14 16:19 UTC, robertsgreibers commented on mroom/api/tests.py
>              content_type='application/json',
Resolved.

2022-01-14 16:21 UTC, robertsgreibers approved these changes

2022-01-14 16:21 UTC, robertsgreibers commented on mroom/settings.py
>  import datetime
Resolved.

2022-01-14 16:21 UTC, robertsgreibers commented on mroom/api/tests.py
>              'date': '2022-10-27T10:01'
Resolved.

2022-01-14 16:22 UTC, robertsgreibers commented on mroom/api/models.py
> +
Resolved.

2022-01-14 16:22 UTC, merged